# Generated by Django 3.2.3 on 2021-07-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']]),
        ),
    ]
